# Generated by Django 4.2.4 on 2023-08-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0007_remove_collection_id_from_nft_attribute'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sell_offer_id',
            field=models.CharField(default='N/A', max_length=300, verbose_name='sell offer id'),
        ),
        migrations.AddField(
            model_name='offer',
            name='buy_offer_id',
            field=models.CharField(default='N/A', max_length=300, verbose_name='buy offer id'),
        ),
        migrations.AddField(
            model_name='offer',
            name='nft',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='nft_offers',
                to='collection.nft',
            ),
        ),
    ]
