# Generated by Django 4.2.4 on 2023-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='banner_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='banner url'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='discord_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='discord link'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='twitter link'),
        ),
    ]
