# Generated by Django 4.2.4 on 2023-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0002_extend_max_length_for_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftattribute',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='value'),
        ),
    ]
