# Generated by Django 4.2.4 on 2023-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0004_nft_owner_column_is_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftattribute',
            name='key',
            field=models.TextField(db_index=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='nftattribute',
            name='value',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='value'),
        ),
    ]
