# Generated by Django 4.2.4 on 2023-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0005_switch_nft_attributes_col_to_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='uri',
            field=models.TextField(blank=True, null=True, verbose_name='uri'),
        ),
    ]
