# Generated by Django 4.2.4 on 2023-08-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0006_make_nft_uri_col_text_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftattribute',
            name='collection',
        ),
        migrations.AlterField(
            model_name='nftattribute',
            name='nft',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='collection.nft'
            ),
        ),
    ]
