# Generated by Django 4.2.4 on 2023-08-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0003_nft_attribute_value_col_is_indexable_and_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='my_nfts',
                to='accounts.account',
            ),
        ),
    ]
